# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='\u59d3\u540d')),
                ('sex', models.IntegerField(choices=[(1, '\u7537'), (2, '\u5973'), (0, '\u672a\u77e5')], verbose_name='\u6027\u522b')),
                ('profession', models.CharField(max_length=128, verbose_name='\u804c\u4e1a')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('qq', models.CharField(max_length=128, verbose_name='QQ')),
                ('phone', models.CharField(max_length=128, verbose_name='\u7535\u8bdd')),
                ('status', models.IntegerField(choices=[(0, '\u7533\u8bf7'), (1, '\u901a\u8fc7'), (2, '\u62d2\u7edd')], verbose_name='\u5ba1\u6838\u72b6\u6001')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u5b66\u5458\u4fe1\u606f',
                'verbose_name_plural': '\u5b66\u5458\u4fe1\u606f',
            },
        ),
    ]
