# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='homephone',
            field=models.CharField(max_length=128, null=True, verbose_name='\u5bb6\u5ead\u7535\u8bdd'),
        ),
    ]
